apiVersion: v1
kind: Pod
metadata:
  name: az1-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
  nodeSelector:
    node-role.kubernetes.io/controlplane: "true"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        preference:
          matchExpressions:
          - key: availability-zone
            operator: In
            values:
            - zone1
      - weight: 20
        preference:
          matchExpressions:
          - key: availability-zone
            operator: In
            values:
            - zone2
